config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :notams, only: [:new, :index] do
    post :upload, on: :collection
  end

end

app/models/notam.rb
class Notam
  class DaysInfo
    include ActiveModel::Model
    ATTRIBUTES = [:mon, :tue, :wed, :thu, :fri, :sat, :sun]

    attr_accessor(*ATTRIBUTES)

    def all
      ATTRIBUTES.each_with_object({}) do |attr, hash|
        hash[attr] = public_send(attr)
      end
    end
  end

  include ActiveModel::Model
  attr_accessor :source, :icao

  def days
    @days ||= DaysInfo.new
  end

  def days=(value)
    @days = DaysInfo.new(value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notams_controller.rb
class NotamsController < ApplicationController
  IncorrectFileType = Class.new(StandardError)
  rescue_from ActionController::ParameterMissing, IncorrectFileType, with: :wrong_or_missing_file
  def index
    render :index, locals: { notams: [] }
  end

  def new; end

  def upload
    validate_file_content_type!
    notams = NotamSelector[file_with_notams]
    render :index, locals: { notams: notams }
  end

  private

  def validate_file_content_type!
    if file_with_notams.content_type != 'text/plain'
      raise IncorrectFileType, "#{file_with_notams.content_type} content type is incorrect"
    end
  end

  def wrong_or_missing_file(ex)
    flash[:error] = ex.message
    redirect_to :root
  end

  def file_with_notams
    @file_with_notams ||= params.require(:source)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :index, locals: { source: readme_source }
  end

  private

  def readme_source
    @readme_source ||= ReadmeReader['README.md']
  rescue ReadmeReader::NotFound
    'Not ready yeat'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def days_list
    [:mon, :tue, :wed, :thu, :fri, :sat, :sun]
  end

  BOOTSTRAP_FLASH_MSG = {
    'success' => 'alert-success',
    'error' => 'alert-danger',
    'alert' => 'alert-warning',
    'notice' => 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type, flash_type.to_s)
  end
end

app/views/application/_menu.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Notam

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to('Welcome', root_path)
      = form_tag(upload_notams_path, multipart: true, :class => 'navbar-form navbar-left navbar-right') do
        %span Uplad file:
        .form-group
          = file_field_tag(:source)
        = submit_tag("Upload file", :class => 'btn btn-default')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NotamReader
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'menu'
    - flash.each do |type, message|
      .alert.fade.in{ :class => bootstrap_class_for(type), role: 'alert'}
        %span= message
    = yield

app/views/notams/index.html.haml
%h1
  Notham list (
  = link_to('Start', :new_notam)
  )
%hr
%table.table.table-striped
  %thead
    %tr
      %td code icao
      - days_list.each do |day_name|
        %td= day_name.to_s.humanize
  %tbody
    - notams.each do |notam|
      %tr
        %td= notam.icao
        - notam.days.all.values.each do |value|
          %td= value

app/views/notams/new.html.haml
= form_tag(upload_notams_path, multipart: true) do
  = file_field_tag(:source)
  = submit_tag("Start processing")

app/views/welcome/index.html.haml
%center
  %h1
    = link_to('Start', :new_notam)
%h1 Details about task
= source.html_safe